import { db } from "./firebase";
import { doc, getDoc, setDoc, collection, updateDoc, increment } from "firebase/firestore";
import { UserInterest, Recommendation } from "../types";

export const trackUserActivity = async (
  userId: string,
  type: string,
  metadata: Record<string, any>
) => {
  const userInterestRef = doc(db, "userInterests", userId);
  
  // Basic interest update logic: increment the interest score for the category/location/type
  const updates: Record<string, any> = {};
  if (metadata.genre) updates[`musicGenres.${metadata.genre}`] = increment(1);
  if (metadata.commune) updates[`locations.${metadata.commune}`] = increment(1);
  updates[`activityTypes.${type}`] = increment(1);
  updates["lastUpdated"] = new Date().toISOString();

  await setDoc(userInterestRef, updates, { merge: true });
};

export const getPersonalizedRecommendations = async (
  userId: string
): Promise<Recommendation[]> => {
  // Placeholder: Fetch recommendations from Firestore generated by the AI agent (server-side)
  // For now, return empty or mock data to avoid errors
  return [];
};
