
/**
 * AFRIGOMBO ELITE - AVATAR LAYERS CONFIGURATION
 * Defines the precise rendering order for the premium engine.
 */

export const AVATAR_RENDER_ORDER: string[] = [
  'arriere_plans',
  'corps',
  'sous_vetement',
  'tete',
  'visage_base',
  'cicatrices',
  'maquillage',
  'yeux',
  'sourcils',
  'nez',
  'bouche',
  'barbe',
  'moustache',
  'tee-shirt',
  'chemise',
  'pantalons',
  'jeans',
  'chaussures',
  'sneakers',
  'veste',
  'manteau',
  'robes',
  'costumes',
  'tenues_africaines',
  'tenues_ivoiriennes',
  'tenues_scene',
  'lunettes',
  'cheveux',
  'casquettes',
  'chapeaux',
  'couronnes',
  'ecouteurs',
  'collier',
  'chaines',
  'montres',
  'bracelets',
  'bagues',
  'sac',
  'ailes',
  'badges',
  'effets_speciaux'
];

export const CATEGORY_LABELS: Record<string, string> = {
  'corps': 'Corps',
  'tete': 'Tête',
  'visage_base': 'Visage',
  'yeux': 'Yeux',
  'sourcils': 'Sourcils',
  'nez': 'Nez',
  'bouche': 'Bouche',
  'barbe': 'Barbe',
  'moustache': 'Moustache',
  'cicatrices': 'Cicatrices',
  'maquillage': 'Maquillage',
  'cheveux': 'Coiffure',
  'tee-shirt': 'T-Shirt',
  'chemise': 'Chemise',
  'veste': 'Veste',
  'manteau': 'Manteau',
  'pantalons': 'Pantalon',
  'jeans': 'Jean',
  'robes': 'Robe',
  'costumes': 'Costume',
  'tenues_africaines': 'Tenue Africaine',
  'tenues_ivoiriennes': 'Tenue Ivoirienne',
  'tenues_scene': 'Tenue de Scène',
  'lunettes': 'Lunettes',
  'casquettes': 'Casquette',
  'chapeaux': 'Chapeau',
  'couronnes': 'Couronne',
  'ecouteurs': 'Écouteurs',
  'collier': 'Collier',
  'chaines': 'Chaîne',
  'montres': 'Montre',
  'bagues': 'Bague',
  'bracelets': 'Bracelet',
  'sac': 'Sac',
  'ailes': 'Ailes',
  'badges': 'Badges',
  'effets_speciaux': 'Effets Spéciaux',
  'arriere_plans': 'Arrière-plan',
  'sneakers': 'Sneakers',
  'sous_vetement': 'Sous-vêtement'
};
